version: '3'

services:
  bdd:
    container_name: mysqlenigma
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: enigma
      MYSQL_DATABASE: enigmadb
    expose:
      - "3306"
    ports:
      - "3308:3306"
    volumes:
      - bdd-data:/var/lib/mysql

volumes:
###> doctrine/doctrine-bundle ###
  bdd-data:
###< doctrine/doctrine-bundle ###
